### ISSUE TITLE
`iter_sample` does not work

### ISSUE THREAD

**Issue by maxschalz** [Nuclear-Verification-and-Disarmament/bicyclus#14]
Using `pm.iter_sample` in `examples/run.py` raises the following error:
```
Traceback (most recent call last):
  File "/home/bicyclus/examples/run.py", line 316, in <module>
    main()
  File "/home/bicyclus/examples/run.py", line 312, in main
    sample(args, pymc_model, initvals)
  File "/home/bicyclus/examples/run.py", line 290, in sample
    for trace in sampler:
  File "/home/anaconda3/envs/pymc-env/lib/python3.10/site-packages/pymc/sampling.py", line 981, in iter_sample
    for i, (strace, _) in enumerate(sampling):
  File "/home/anaconda3/envs/pymc-env/lib/python3.10/site-packages/pymc/sampling.py", line 1062, in _iter_sample
    point, stats = step.step(point)
  File "/home/anaconda3/envs/pymc-env/lib/python3.10/site-packages/pymc/step_methods/arraystep.py", line 155, in step
    apoint = DictToArrayBijection.map({v.name: point[v.name] for v in self.vars})
  File "/home/anaconda3/envs/pymc-env/lib/python3.10/site-packages/pymc/step_methods/arraystep.py", line 155, in <dictcomp>
    apoint = DictToArrayBijection.map({v.name: point[v.name] for v in self.vars})
KeyError: 'feed_assay_interval__'
```

I am currently investigating the error. Both `pm.sample` and `pm.iter_sample` eventually call `pymc/sampling.py:1025` (function `_iter_sample`) to perform the sampling. I suspect that `pm.sample` does *something* to the initial values that transforms them into the correct format, compare the following `pdb` output:

- Using `pm.sample`:
  ```
  (Pdb) w
    /home/bicyclus/toymodel/toymodel.py(452)<module>()
  -> main()
    /home/bicyclus/toymodel/toymodel.py(447)main()
  -> arviz_summary, trace, emu, solver_str = run_simulations(model, **kwargs)
    /home/bicyclus/toymodel/toymodel.py(291)run_simulations()
  -> trace = pm.sample(
    /home/anaconda3/envs/pymc-env/lib/python3.10/site-packages/pymc/sampling.py(655)sample()
  -> mtrace = _sample_many(**sample_args)
    /home/anaconda3/envs/pymc-env/lib/python3.10/site-packages/pymc/sampling.py(769)_sample_many()
  -> trace = _sample(
    /home/anaconda3/envs/pymc-env/lib/python3.10/site-packages/pymc/sampling.py(915)_sample()
  -> for it, (strace, diverging) in enumerate(sampling):
    /home/anaconda3/envs/pymc-env/lib/python3.10/site-packages/fastprogress/fastprogress.py(41)__iter__()
  -> for i,o in enumerate(self.gen):
  > /home/anaconda3/envs/pymc-env/lib/python3.10/site-packages/pymc/sampling.py(1025)_iter_sample()
  -> model = modelcontext(model)
  (Pdb) start
  {'large_norm_interval__': array(1.44301298), 'small_unif_interval__': array(-0.17056391)}
  ```
- Using `pm.iter_sample`:
  ```
  (Pdb) w
    /home/bicyclus/toymodel/toymodel.py(452)<module>()
  -> main()
    /home/bicyclus/toymodel/toymodel.py(447)main()
  -> arviz_summary, trace, emu, solver_str = run_simulations(model, **kwargs)
    /home/bicyclus/toymodel/toymodel.py(283)run_simulations()
  -> for trace in sampler:
    /home/anaconda3/envs/pymc-env/lib/python3.10/site-packages/pymc/sampling.py(981)iter_sample()
  -> for i, (strace, _) in enumerate(sampling):
  > /home/anaconda3/envs/pymc-env/lib/python3.10/site-packages/pymc/sampling.py(1025)_iter_sample()
  -> model = modelcontext(model)
  (Pdb) start
  {'large_norm': 7559.40626711426, 'small_unif': 0.2070833560593321}
  ```

**Comment by maxschalz** [comment]
In [`pymc/sample.py:554`](https://github.com/pymc-devs/pymc/blob/372d7c247ac55bd90ed999031a4e207fa24757be/pymc/sampling.py#L552-L560):
```python
    if initial_points is None:
        # Time to draw/evaluate numeric start points for each chain.
        ipfns = make_initial_point_fns_per_chain(
            model=model,
            overrides=initvals,
            jitter_rvs=filter_rvs_to_jitter(step),
            chains=chains,
        )
        initial_points = [ipfn(seed) for ipfn, seed in zip(ipfns, random_seed_list)]
```
This is where the `large_norm_interval__` initial values are created, and this is missing in `iter_sample`. I have to consult with PyMC people to find out if this is a PyMC bug or if it is the desired behaviour.

**Comment by maxschalz** [comment]
I always used `pm.iter_sample` to do stuff after samples got accepted (e.g., save Cyclus output to file). This is not possible anymore because of the bug. However, the (PyMC-preferred) way to do it is to use `pm.sample`'s `callback` kwarg: https://www.pymc.io/projects/examples/en/latest/howto/sampling_callback.html

**Comment by maxschalz** [comment]
I will close this issue for now and continue discussion in #15 .
